server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    #host: 114.116.248.80
    port: 6379
    password: 456123z
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 0
  datasource:
    url: jdbc:mysql://114.116.248.80:3306/wordcute?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 456123z
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml



log:
  path: /data/log/wordcute
  level: info

