server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://114.116.248.80:3306/wordcute?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 456123z
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml

log:
  path: /data/log/wordcute
  level: info
